"""Add telegram_id

Revision ID: 06fba3687953
Revises: fd429d74b439
Create Date: 2025-05-03 13:32:47.951247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06fba3687953'
down_revision = 'fd429d74b439'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telegram_id', sa.BigInteger(), nullable=True))
        batch_op.alter_column('avatar_url',
               existing_type=sa.VARCHAR(length=255),
               type_=sa.String(length=256),
               existing_nullable=True)
        batch_op.alter_column('color',
               existing_type=sa.VARCHAR(length=7),
               type_=sa.String(length=8),
               existing_nullable=True)
        batch_op.create_unique_constraint('uq_user_telegram_id', ['telegram_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('color',
               existing_type=sa.String(length=8),
               type_=sa.VARCHAR(length=7),
               existing_nullable=True)
        batch_op.alter_column('avatar_url',
               existing_type=sa.String(length=256),
               type_=sa.VARCHAR(length=255),
               existing_nullable=True)
        batch_op.drop_column('telegram_id')

    # ### end Alembic commands ###
